### ISSUE TITLE
Not random randomizing

### ISSUE THREAD

**Issue by devurose** [MoonJuiceDev/BuyRateSettings#3]
Hey there! I'm loving the mod so far, definitely staying in my modpack indefinitely!!
Though I have noticed, I'm consistently getting the same order of buy rates on new save files, starting with 93%, then 76% and so on.
I'm not sure if this is unintended, or if I just did my config wrong haha, either way just wanted to open up an issue about this just incase^^

Thank you for your time!

**Comment by MoonJuiceDev** [comment]
Hey I'm glad you like it! :)

I'm unable to reproduce this bug, however getting 93% on the first day is expected: the rate is based off of the random map seed that the game generates, and starting a new save will _always have a seed of **0**_ until you pull the lever to start playing (thus generating a seed).

I tried a few different fresh saves just now to test and these were my results each day:

- **1st Save:** _93 -> 105 -> 59_
- **2nd Save:** _93 -> 50 -> 76_
- **3rd Save:** _93 -> 107 -> 84_
- **4th Save:** _93 -> 65 -> 74_

If you continue to notice the rates being in the same order on each new save, send me the config file or a profile code and I can look further into it.

**Comment by devurose** [comment]
Oh that totally makes sense! I had no idea it's based off of the seed, which in retrospect was kind of obvious, my bad haha
Regardless, I appreciate the answer, have an amazing day!
